#spring:
#  datasource:
#    url: jdbc:oracle:thin:@10.56.19.243:1521/xnb
#    username: lnxnbapp
#    password: lnxnbapp

spring:
  datasource:
    name: main.datasource
    url: jdbc:mysql://localhost:3306/be_payment?useUnicode=true&characterEncoding=UTF-8
    username: lygjoint
    password: lygjoint

#spring:
#  datasource:
#    url: jdbc:mysql://192.168.129.251:3306/joint_demo?useUnicode=true&characterEncoding=UTF-8
#    username: joint_demo
#    password: joint_demo
#    name: local-mysql

center:
  s90001: http://192.168.163.206:7007/provisional-certificate/petition/si371300/cxyl/web
  s90002: http://192.168.163.206:7007/provisional-certificate/petition/si371300/cxyal/web
  s90003: http://192.168.163.206:7007/provisional-certificate/petition/si371300/feehistory/web

http:
  targetAttribute:
    token: MIGfMA0GCSqGSIb3DQEa
    toUser: 860001
    fromUser: 800002
    nonce: 0
    createTime: 0
    msgType: json
